spring.application.name=Canarypets

spring.jpa.hibernate.ddl-auto=update

# Nota: A día de hoy no es necesario de usar con spring moderno - Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Evitar warnings - Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect #Importante: El dialecto MySQL8Dialect ya no existe en Hibernate moderno
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect # En caso de querer forzar el dialecto, se usa MySQLDialect (unificado)
# En spring moderno (Hibernate 6+) realmente no es necesario usarlo, ya que Spring Boot detecta automáticamente el dialecto desde la conexión JDBC.

# Mantener las rutas estáticas por defecto + añadir ruta hacia el volumen de imágenes - Recursos estáticos
spring.web.resources.static-locations=classpath:/static/,file:/app/

# Naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Logs
logging.file.name=/app/logs/app.log

# Para forzar UTF-8 en Spring Boot
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Para evitar que Tomcat falle al decodificar parámetros GET y forzar encoding en Tomcat (CLAVE)
server.tomcat.uri-encoding=UTF-8
server.tomcat.use-relative-redirects=true
# Lo último no es siempre necesario, pero evita problemas con redirects + encoding

# Relajar parsing de caracteres en Tomcat
server.tomcat.relaxed-query-chars=|,{,},[,],^,`,<,>,"
server.tomcat.relaxed-path-chars=|,{,},[,],^,`,<,>,"